services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\PhoenixApi\PhoenixApiClientInterface:
        alias: App\PhoenixApi\PhoenixApiClient

    App\PhoenixApi\PhoenixApiClient:
        arguments:
            $client: '@phoenix'
            $requestStack: '@request_stack'
            $importToken: '%env(string:default::PHOENIX_IMPORT_TOKEN)%'

    App\Middleware\TraceIdMiddleware:
